# Generated by Django 4.2.5 on 2023-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.PositiveIntegerField()),
                ('blank_image', models.PositiveIntegerField()),
                ('success_image', models.PositiveIntegerField()),
                ('failure_image', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
