# Generated by Django 4.2.5 on 2023-09-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='count_date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
