# Generated by Django 4.2.5 on 2023-09-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
                ('reg_date', models.DateField()),
                ('success_status', models.PositiveIntegerField()),
                ('memo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
