# Generated by Django 4.2.5 on 2023-09-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_challenge_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='user_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
